# Generated by Django 5.2.3 on 2025-06-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
