# Generated by Django 5.2.3 on 2025-06-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
